name: Build and test

on:
  pull_request:
  push:
    paths-ignore:
      - 'README.md'
    branches:
      - develop
      - main

jobs:
  debug_build:
    name: Debug build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        run: ./gradlew assembleDebug

  release_build:
    name: Release build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Build
        run: ./gradlew assembleRelease

  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Unit tests
        run: ./gradlew testDebug --stacktrace

      - name: Upload testDebugUnitTest results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: testDebugUnitTest
          path: ./**/build/reports/tests/testDebugUnitTest